[pytest]
testpaths = tests
markers =
    smoke: basic render checks
    step_3: authentication and application shell checks
    step_4_createUser: users create test
    step_4_viewList: users list test
    step_4_editUser: users edit test
    step_4_deleteOne: users single delete test
    step_4_deleteAll: users bulk delete test
    step_5_createStatus: statuses create test
    step_5_viewList: statuses list test
    step_5_editStatus: statuses edit test
    step_5_deleteOne: statuses single delete test
    step_5_deleteAll: statuses bulk delete test
    step_6_createLabel: labels create test
    step_6_viewList: labels list test
    step_6_editLabel: labels edit test
    step_6_deleteOne: labels single delete test
    step_6_deleteAll: labels bulk delete test
    step_7_createTasks: tasks create test
    step_7_viewBoard: tasks board/details test
    step_7_editTasks: tasks edit test
    step_7_dragAndDropTasks: tasks status change test
    step_7_deleteTasks: tasks delete test
