sonar.projectKey=AmidamaruQ_qa-auto-engineer-python-tw-project-314
sonar.organization=amidamaruq
sonar.python.coverage.reportPaths=coverage.xml
sonar.sources=pages,utils,config.py,settings.py
sonar.tests=tests
sonar.test.inclusions=tests/test_*.py


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=qa-auto-engineer-python-tw-project-314
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
