import uuid

import pytest


@pytest.fixture
def tasks_setup(statuses_page, users_page, tasks_page):
    assert statuses_page.delete_all_statuses()
    primary_status_name = f"Status_{uuid.uuid4().hex[:5]}"
    primary_status_slug = f"primary-{uuid.uuid4().hex[:5]}"
    secondary_status_name = f"Status_{uuid.uuid4().hex[:5]}"
    secondary_status_slug = f"secondary-{uuid.uuid4().hex[:5]}"

    assert statuses_page.create_status(
        primary_status_name,
        primary_status_slug,
    )
    assert statuses_page.create_status(
        secondary_status_name,
        secondary_status_slug,
    )

    email = f"tasker_{uuid.uuid4().hex[:5]}@example.com"
    first_name = f"Tasker{uuid.uuid4().hex[:4]}"
    last_name = "Tester"
    assert users_page.create_user(email, first_name, last_name)

    tasks_page.open_page()

    return {
        "page": tasks_page,
        "assignee_email": email,
        "status": primary_status_name,
        "alt_status": secondary_status_name,
        "content": "Autogenerated_by_selenium",
    }


def test_create_task_shows_card(tasks_setup):
    ctx = tasks_setup
    title = f"Task_{uuid.uuid4().hex[:6]}"

    assert ctx["page"].create_task(
        title,
        ctx["content"],
        ctx["assignee_email"],
        ctx["status"],
    )
    assert ctx["page"].task_exists(title)


def test_edit_task_updates_title(tasks_setup):
    ctx = tasks_setup
    original_title = f"Task_{uuid.uuid4().hex[:6]}"
    updated_title = f"{original_title}_Updated"

    assert ctx["page"].create_task(
        original_title,
        ctx["content"],
        ctx["assignee_email"],
        ctx["status"],
    )
    assert ctx["page"].edit_task(
        original_title,
        new_title=updated_title,
    )
    assert ctx["page"].task_exists(updated_title)


def test_change_task_status_moves_card(tasks_setup):
    ctx = tasks_setup
    title = f"Task_{uuid.uuid4().hex[:6]}"

    assert ctx["page"].create_task(
        title,
        ctx["content"],
        ctx["assignee_email"],
        ctx["status"],
    )
    assert ctx["page"].edit_task(
        title,
        new_status=ctx["alt_status"],
    )
    assert ctx["page"].is_task_in_status(title, ctx["alt_status"])


def test_view_task_details(tasks_setup):
    ctx = tasks_setup
    title = f"Task_{uuid.uuid4().hex[:6]}"
    content = f"Detailed_{ctx['content']}"

    assert ctx["page"].create_task(
        title,
        content,
        ctx["assignee_email"],
        ctx["status"],
    )

    ctx["page"].open_task_details(title)
    ctx["page"].wait_for_text(ctx["assignee_email"])
    ctx["page"].wait_for_text(title)
    ctx["page"].wait_for_text(content)
